---
resources: 
-   name: pg-ci-pipeline-repo
    type: git
    source: 
        uri: https://github.com/ranjaa2/pg-ci-pipeline-repo.git

jobs: 
-   name: pg-ci-test
    plan: 
    -   get: pg-ci-pipeline-repo
    -   task: execute-psql
        file: pg-ci-pipeline-repo/tasks/pg-test/task.yml
        
