---
resources: 
-   name: pipeline-repo
    type: git
    source: 
        uri: https://github.com/concourse-courses/004-your-first-pipeline.git

jobs: 
-   name: hello-world
    plan: 
    -   get: pipeline-repo
    -   task: say-hello
        file: pipeline-repo/tasks/hello-world/task.yml
        
