---
platform: linux

image_resource: 
    type: docker-image
    source: 
        repository: alpine

run:
    path: sh
    args:
    -   -exc
    -   |
        pg-ci-pipeline-repo/scripts/exc-psql.sh

